name: CI
on:
  push:
    branches: [ main ]
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  uberfx-server:
    name: uberfx-server
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest ] # windows-latest,
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with: { go-version: '1.21' }

      - name: Download dependencies
        run: go mod download
      - name: Install
        run: go install .

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with: { version: latest }
